@startuml MCD Biblio
abstract class ressource
class livre
class film
class enregistrement_musical
enum type
class exemplaire
enum etat 
class contributeur
class contributeur_ressource

class compte_personnel
class personnel 
class compte_adherant
class adherant

class pret 
class reservation
/'
class ajout_ressource
class modif_ressource
class ajout_exemplaire
class modif_exemplaire
'/
annotation annotation


skinparam groupInheritance 2
ressource <|-- livre
ressource <|-- film
ressource <|-- enregistrement_musical



livre "*" -- "1..*" contributeur
(livre, contributeur) . auteur
enregistrement_musical "*" -- "1..*" contributeur
(enregistrement_musical, contributeur) . compositeur
enregistrement_musical "*" -- "1..*" contributeur
(enregistrement_musical, contributeur) . interprete
film "*" -- "1..*" contributeur
(film, contributeur) . realisateur
film "*" -- "1..*" contributeur
(film, contributeur) . acteur





ressource *-- "*" exemplaire

compte_personnel "1" -- "1" personnel
compte_personnel "*" -- "*" ressource
/'
compte_personnel "*" -- "*" ressource
(compte_personnel, ressource) . ajout_ressource
compte_personnel "*" -- "*" ressource
(compte_personnel, ressource) . modif_ressource
compte_personnel "*" -- "*" exemplaire
(compte_personnel, exemplaire) . ajout_exemplaire
compte_personnel "*" -- "*" exemplaire
(compte_personnel, exemplaire) . modif_exemplaire
'/
compte_adherant "1" -- "1" adherant
compte_adherant "*" -- "*" exemplaire
(compte_adherant, exemplaire) . reservation
compte_adherant "*" -- "*" exemplaire
(compte_adherant, exemplaire) . pret

enum etat{
    neuf 
    bon
    abime 
    perdu
}

enum situation{
    normal
    suspendu
    blackliste

}

class ressource{
    'Numeric manque paramètre
    code : numeric {key}
    titre : text
    dateApparition : date 
    editeur : text
    genre : text
    codeClassification :numeric
}

class contributeur{
    nom : text
    prenom : text
    dateNaissance : date
    nationalite : text
}

class livre{
    ISBN : numeric {key}
    resume : text
    langue : text
}

class film{
    longeur : integer
    langue : text
}

class enregistrement_musical{
    longeur : integer
    synopsis : text
    langue : text
}

class exemplaire{
    idExemplaire : numeric
    etat : etat
}

class personnel{
    nom : text
    prenom : text
    adresse : text
    email : text
}

class compte_personnel{
    login : text {key}
    motDePasse : text
}

class contributeur_ressource{
    fonction : text
}

class adherant{
    numeroCarte : numeric {key}
    nom : text
    prenom : text
    dateNaissance : date
    adresse : text
    email : text
    telephone : numeric
}

'Un héritage pour compte_adhérant?

class compte_adherant{
    login : text {key}
    motDePasse : text
    etatCompte : boolean
    suspenduJusque : date {optional}
    sommeDu : integer
    blackliste : boolean
    actuelle : boolean
}

class pret{
    dateEmprunte : date
    dureeLimitee : integer
    dateRetourne : date {optional}
    etatRetourne : etat {optional}
}

class reservation{
    dateReserve : date
}

@enduml
